name: Deploy HeartoListen App

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Build app with API key
      run: |
        # Create a copy of index.html with the API key injected
        if [ ! -z "${{ secrets.OPENAI_API_KEY }}" ]; then
          echo "Injecting API key into app..."
          # Replace the backend API call with direct OpenAI API call using the secret
          sed -i "s|/api/chat|https://api.openai.com/v1/chat/completions|g" index.html
          # Add the API key to the fetch headers (this is just for demo - not recommended for production)
          echo "API key configured"
        else
          echo "No API key found, using fallback responses only"
        fi
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
